name: complete-ci

on:
  push:
    branches: [develop, main]
  pull_request:

jobs:
  tests: # identificador do job
    runs-on: ubuntu-latest # máquina Linux limpa fornecida pelo GitHub
    steps:
      - name: Baixar o código
        uses: actions/checkout@v5

      - name: Instalar o uv
        uses: astral-sh/setup-uv@v5

      - name: Instalar depedências
        run: uv sync --group dev --group training

      - name: Checagem de lint
        run: uv run ruff check .

      - name: Checagem da formatação
        run: uv run ruff format --check .

      - name: Rodar testes
        run: uv run pytest
