name: complete-ci

# Gatilho: roda em todo push e em todo pull request
on:
  push:
    branches: [develop, main]
  pull_request: 

jobs:
  tests:                                      # identificador do job
    runs-on: ubuntu-latest                    # máquina Linux limpa fornecida pelo GitHub
  steps:
    - name: Baixar o código
      uses: actions/checkout@v4

    - name: Instalar o uv
      uses: astral-sh/setup-uv@v5

    - name: Instalar depedências
      run: uv sync --group dev

    - name: Rodar testes
      run: uv run pytest
